apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: declarative-api
  description: API for NGINX Declarative Configuration
spec:
  type: openapi
  lifecycle: production
  owner: team-Golam
  definition: |
    openapi: 3.0.0
    info:
      title: NGINX Declarative API
      version: 1.0.0
    servers:
      - url: http://192.168.159.134
        description: Nginx Declarative API Server
    paths:
      /v5.0/config:
        post:
          summary: Publish configuration to NGINX
          operationId: publishConfig
          requestBody:
            description: Configuration to be published
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    output:
                      type: object
                      properties:
                        type:
                          type: string
                          example: "nms"
                        nms:
                          type: object
                          properties:
                            url:
                              type: string
                              example: "https://192.168.159.134"
                            username:
                              type: string
                              example: "admin"
                            password:
                              type: string
                              example: "ziY5BZbZmpd43O8xVGi13ocbpSnw8P"
                            instancegroup:
                              type: string
                              example: "declarativeAPITest"
                            synctime:
                              type: integer
                              example: 0
                            modules:
                              type: array
                              items:
                                type: string
                  example:
                    output:
                      type: "nms"
                      nms:
                        url: "https://192.168.159.134"
                        username: "admin"
                        password: "ziY5BZbZmpd43O8xVGi13ocbpSnw8P"
                        instancegroup: "declarativeAPITest"
                        synctime: 0
                        modules: []
                    declaration:
                      http:
                        servers:
                          - name: "Petstore API"
                            names:
                              - "apigw.nginx.lab"
                            resolver: "8.8.8.8"
                            listen:
                              address: "80"
                            log:
                              access: "/var/log/nginx/apigw.nginx.lab-access_log"
                              error: "/var/log/nginx/apigw.nginx.lab-error_log"
                            locations:
                              - uri: "/petstore"
                                urimatch: "prefix"
                                apigateway:
                                  openapi_schema:
                                    content: "http://petstore.swagger.io/v2/swagger.json"
                                  api_gateway:
                                    enabled: true
                                    strip_uri: true
                                    server_url: "https://petstore.swagger.io/v2"
                                  rate_limit:
                                    - profile: "petstore_ratelimit"
                                      httpcode: 429
                                      burst: 0
                                      delay: 0
                                      enforceOnPaths: true
                                      paths:
                                        - "/user/login"
                                        - "/user/logout"
                                log:
                                  access: "/var/log/nginx/petstore-access_log"
                                  error: "/var/log/nginx/petstore-error_log"
                        rate_limit:
                          - name: "petstore_ratelimit"
                            key: "$binary_remote_addr"
                            size: "10m"
                            rate: "2r/s"
          responses:
            '200':
              description: Successfully published the configuration
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      code:
                        type: integer
                        example: 200
                      content:
                        type: object
                        properties:
                          createTime:
                            type: string
                            example: "2024-08-13T04:48:30.856421821Z"
                          details:
                            type: object
                            properties:
                              failure:
                                type: array
                                items:
                                  type: string
                              pending:
                                type: array
                                items:
                                  type: string
                              success:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: "f5nafizraafidapiserver"
                          id:
                            type: string
                            example: "f580bba6-fd3c-4b8c-95d0-819b5474c624"
                          message:
                            type: string
                            example: "Instance Group config successfully published to declarativeAPITest"
                          status:
                            type: string
                            example: "successful"
                          updateTime:
                            type: string
                            example: "2024-08-13T04:48:32.641811707Z"
                      configUid:
                        type: string
                        example: "513037b1-ce33-40c6-a884-92728c626877"

