apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: nginx-declarative-api
  description: API to configure NGINX declaratively using a JSON payload
spec:
  type: openapi
  lifecycle: production
  owner: team-Golam
  definition: |
    openapi: 3.0.0
    info:
      title: NGINX Declarative API
      version: 1.0.0
      description: |
        This API allows you to configure NGINX servers, locations, and rate limits declaratively using JSON payloads.
    paths:
      /v5.0/config:
        post:
          summary: Configure NGINX
          operationId: configureNginx
          requestBody:
            description: JSON payload to configure NGINX
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    output:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - nms
                        nms:
                          type: object
                          properties:
                            url:
                              type: string
                              format: uri
                            username:
                              type: string
                            password:
                              type: string
                            instancegroup:
                              type: string
                            synctime:
                              type: integer
                            modules:
                              type: array
                              items:
                                type: string
                    declaration:
                      type: object
                      properties:
                        http:
                          type: object
                          properties:
                            servers:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  names:
                                    type: array
                                    items:
                                      type: string
                                  resolver:
                                    type: string
                                  listen:
                                    type: object
                                    properties:
                                      address:
                                        type: string
                                  log:
                                    type: object
                                    properties:
                                      access:
                                        type: string
                                      error:
                                        type: string
                                  locations:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        uri:
                                          type: string
                                        urimatch:
                                          type: string
                                          enum:
                                            - prefix
                                        apigateway:
                                          type: object
                                          properties:
                                            openapi_schema:
                                              type: object
                                              properties:
                                                content:
                                                  type: string
                                                  format: uri
                                            api_gateway:
                                              type: object
                                              properties:
                                                enabled:
                                                  type: boolean
                                                strip_uri:
                                                  type: boolean
                                                server_url:
                                                  type: string
                                                  format: uri
                                            rate_limit:
                                              type: array
                                              items:
                                                type: object
                                                properties:
                                                  profile:
                                                    type: string
                                                  httpcode:
                                                    type: integer
                                                  burst:
                                                    type: integer
                                                  delay:
                                                    type: integer
                                                  enforceOnPaths:
                                                    type: boolean
                                                  paths:
                                                    type: array
                                                    items:
                                                      type: string
                                        log:
                                          type: object
                                          properties:
                                            access:
                                              type: string
                                            error:
                                              type: string
                            rate_limit:
                              type: array
                              items:
                                type: object
                                properties:
                                  name:
                                    type: string
                                  key:
                                    type: string
                                  size:
                                    type: string
                                  rate:
                                    type: string
          responses:
            '200':
              description: Successfully configured NGINX
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      code:
                        type: integer
                      content:
                        type: object
                        properties:
                          createTime:
                            type: string
                            format: date-time
                          details:
                            type: object
                            properties:
                              failure:
                                type: array
                                items:
                                  type: string
                              pending:
                                type: array
                                items:
                                  type: string
                              success:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                          id:
                            type: string
                          message:
                            type: string
                          status:
                            type: string
                          updateTime:
                            type: string
                            format: date-time
                      configUid:
                        type: string
          examples:
            application/json:
              value:
                output:
                  type: nms
                  nms:
                    url: "https://192.168.159.134"
                    username: "admin"
                    password: "ziY5BZbZmpd43O8xVGi13ocbpSnw8P"
                    instancegroup: "declarativeAPITest"
                    synctime: 0
                    modules: []
                declaration:
                  http:
                    servers:
                      - name: "Petstore API"
                        names:
                          - "apigw.nginx.lab"
                        resolver: "8.8.8.8"
                        listen:
                          address: "80"
                        log:
                          access: "/var/log/nginx/apigw.nginx.lab-access_log"
                          error: "/var/log/nginx/apigw.nginx.lab-error_log"
                        locations:
                          - uri: "/petstore"
                            urimatch: "prefix"
                            apigateway:
                              openapi_schema:
                                content: "http://petstore.swagger.io/v2/swagger.json"
                              api_gateway:
                                enabled: true
                                strip_uri: true
                                server_url: "https://petstore.swagger.io/v2"
                              rate_limit:
                                - profile: "petstore_ratelimit"
                                  httpcode: 429
                                  burst: 0
                                  delay: 0
                                  enforceOnPaths: true
                                  paths:
                                    - "/user/login"
                                    - "/user/logout"
                            log:
                              access: "/var/log/nginx/petstore-access_log"
                              error: "/var/log/nginx/petstore-error_log"
                    rate_limit:
                      - name: "petstore_ratelimit"
                        key: "$binary_remote_addr"
                        size: "10m"
                        rate: "2r/s"

