site_name: Project Documentation
site_description: An informative description
repo_url: https://github.com/raafiakram/backstage_api_docs/tree/develop/docs
plugins:
  - techdocs-core
nav:
  - Getting Started: index.md
  - Additional Doc: API_Documentation.md
