apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tirzok-api
  description: An example API
spec:
  type: openapi
  lifecycle: production
  owner: team-Golam
  definition: |
    openapi: 3.0.0
    info:
      title: Nginx apis
      version: 1.0.0
    paths:
      /example:
        get:
          summary: Payment endpoint
          responses:
            '200':
              description: Successful response

